import { app } from 'electron'
import { randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'

/** The tiny generated launcher installed into Resolve's Scripts folder. No other file goes there:
 * every `.lua` (and sub-folder) in that directory becomes its own Workspace → Scripts menu entry. */
const LAUNCHER_FILE_NAME = 'UPPELETE.lua'

export type ResolvePluginInfo = { supported: boolean; installed: boolean; upToDate: boolean; scriptPath: string | null }

export type LaunchSpec =
  | { kind: 'windows'; exe: string; args: string[] }
  | { kind: 'mac-app'; exe: string; args: string[] }
  | { kind: 'exec'; exe: string; args: string[] }

/** Resolve only looks in one fixed per-platform "Utility" scripts folder; there is no way to point
 * it elsewhere. Unsupported on any platform other than Windows/macOS. */
export function resolveScriptsDir(platform: NodeJS.Platform): string | null {
  if (platform === 'win32') return path.join(app.getPath('appData'), 'Blackmagic Design', 'DaVinci Resolve', 'Support', 'Fusion', 'Scripts', 'Utility')
  if (platform === 'darwin') return path.join(app.getPath('home'), 'Library', 'Application Support', 'Blackmagic Design', 'DaVinci Resolve', 'Fusion', 'Scripts', 'Utility')
  return null
}

/** Where `bridge.lua`/`json.lua` actually live: bundled as `extraResources` in a packaged build,
 * or read straight from the repo in dev. The launcher `dofile`s from here, so bridge updates ship
 * with the app itself rather than needing a plugin reinstall. */
export function bridgeResourcesDir(): string {
  return app.isPackaged ? path.join(process.resourcesPath, 'resolve') : path.join(app.getAppPath(), 'resources', 'resolve')
}

/** `<userData>/resolve-bridge`: the mailbox directory both sides poll. */
export function mailboxDir(): string {
  return path.join(app.getPath('userData'), 'resolve-bridge')
}

/** How the Lua launcher should start UPPELETE if it isn't already running. */
export function launchSpec(): LaunchSpec {
  if (app.isPackaged && process.platform === 'win32') return { kind: 'windows', exe: process.execPath, args: [] }
  if (app.isPackaged && process.platform === 'darwin') {
    // process.execPath is `<bundle>.app/Contents/MacOS/<name>`; `open -a` wants the bundle itself.
    const bundlePath = process.execPath.replace(/\/Contents\/MacOS\/[^/]+$/, '')
    return { kind: 'mac-app', exe: bundlePath, args: [] }
  }
  return { kind: 'exec', exe: process.execPath, args: [app.getAppPath()] }
}

function rejectUnsafePath(value: string, label: string): void {
  if (value.includes('"') || value.includes(']]')) throw new Error(`${label} cannot be used as a Resolve script path (contains '"' or ']]'): ${value}`)
}

/** Lua long-bracket string literal: avoids backslash-escaping Windows paths, at the cost of never
 * allowing a literal `]]` inside — checked by `rejectUnsafePath`. */
function luaLongString(value: string): string {
  rejectUnsafePath(value, 'Path')
  return `[[${value}]]`
}

function luaArgsTable(args: string[]): string {
  return `{ ${args.map((arg) => luaLongString(arg)).join(', ')} }`
}

function generateLauncherContent(): string {
  const launch = launchSpec()
  const launchFields = `kind = "${launch.kind}", exe = ${luaLongString(launch.exe)}, args = ${luaArgsTable(launch.args)}`
  return `-- Generated by UPPELETE. Reinstall from UPPELETE → Settings → DaVinci Resolve if UPPELETE moves.\n`
    // Resolve runs each menu script with its own globals, and a file loaded from it doesn't see them, so the
    // config and Resolve's scripting globals are passed to bridge.lua as arguments.
    + `local KATHACUT = { resourcesDir = ${luaLongString(bridgeResourcesDir())}, mailboxDir = ${luaLongString(mailboxDir())}, launch = { ${launchFields} } }\n`
    + `local bridge = assert(loadfile(KATHACUT.resourcesDir .. "/bridge.lua"))\n`
    + `bridge(KATHACUT, Resolve, bmd)\n`
}

export async function pluginInfo(): Promise<ResolvePluginInfo> {
  const dir = resolveScriptsDir(process.platform)
  if (!dir) return { supported: false, installed: false, upToDate: false, scriptPath: null }
  const scriptPath = path.join(dir, LAUNCHER_FILE_NAME)
  try {
    const current = await readFile(scriptPath, 'utf8')
    return { supported: true, installed: true, upToDate: current === generateLauncherContent(), scriptPath }
  } catch {
    return { supported: true, installed: false, upToDate: false, scriptPath }
  }
}

export async function installPlugin(): Promise<ResolvePluginInfo> {
  const dir = resolveScriptsDir(process.platform)
  if (!dir) throw new Error('DaVinci Resolve scripting is only supported on Windows and macOS.')
  await mkdir(dir, { recursive: true })
  const scriptPath = path.join(dir, LAUNCHER_FILE_NAME)
  const temporaryPath = `${scriptPath}.${randomUUID()}.tmp`
  await writeFile(temporaryPath, generateLauncherContent(), 'utf8')
  await rename(temporaryPath, scriptPath)
  return pluginInfo()
}

export async function uninstallPlugin(): Promise<ResolvePluginInfo> {
  const dir = resolveScriptsDir(process.platform)
  if (dir) await rm(path.join(dir, LAUNCHER_FILE_NAME), { force: true })
  return pluginInfo()
}
